name: ODM Docker Run

on:
  workflow_dispatch:

jobs:
  run-odm:
    runs-on: test-larger-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run ODM in Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/datasets/code opendronemap/odm --project-path /datasets
